version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: stock-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"  # host:container
    environment:
      MONGO_INITDB_DATABASE: stock-management
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: 